name: Java Sping CI with Gradle

on:
  push:
    branches: [ master, develop, feat/ci/cd ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Unit and Integration tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: todo
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Test with Gradle
        run: ./gradlew test
